### ISSUE TITLE
(singularity) conda info --json' returned non-zero exit status

### ISSUE THREAD

**Issue by ktmeaton** [Wytamma/snk#58]
I'm experiencing an error with `--use-singularity` when my host system has `conda`, but the global singularity container does not (ex. [nextstrain/base](https://hub.docker.com/r/nextstrain/base/)).

## Error

```text
subprocess.CalledProcessError: Command ' singularity --quiet --silent exec --home '<...>/Projects/Nextstrain'  <...>/miniconda3/envs/snk-pulp/snk/pipelines/ncov/.singularity/850ba3fff0b9dce9f39fe118a4653914.simg sh -c 'conda info --json'' returned non-zero exit status 255.
```

## Proposed Solution

If the host system has `conda` (ex. `conda_found=true`), `snk` will automatically set `--use-conda`.  This is a problem when using a global singularity container which doesn't have `conda` within it.
https://github.com/Wytamma/snk/blob/923651a1425d875dd3ff1b877aabd48b5b92e35e/snk/cli/subcommands/run.py#L209-L214

I can fix this error by changing the `or` check to an `and`, from: https://github.com/Wytamma/snk/blob/923651a1425d875dd3ff1b877aabd48b5b92e35e/snk/cli/subcommands/run.py#L209

to 

```python
if conda_found and self.snk_config.require_conda:
```

Would this be a viable solution to support global singularity containers? Or does this have unintended consequences for using the `conda` runtime?

## Steps to Reproduce

1. Install Singularity.

    ```bash
    conda install singularity=3.8.6
    ```

1. Install a Nextstrain pipeline.

    ```bash
    snk install nextstrain/ncov --commit 024910d7
    ```

1. Add the [nextstrain/base](https://hub.docker.com/r/nextstrain/base/) image as a global singularity container.

    ```bash
    sed -i "1i container: \"docker://nextstrain/base:build-20231212T145331Z\"\n" $CONDA_PREFIX/snk/pipelines/ncov/Snakefile
    ```

1. Run the pipeline.

    > Without the proposed `or` -> `and` fix this generates an error. With the fix, it runs successfully.

    ```bash
    ncov run \
      -r data -r defaults -r nextstrain_profiles -r scripts \
      --profile nextstrain_profiles/nextstrain-ci \
      --use-singularity
    ```

**Comment by Wytamma** [comment]
Hi @ktmeaton,

Thanks for creating the issue! Because `require_conda` defaults to `False` adding the `and` means that the `--use-conda` will never be passed to snakemake (unless you include a `snk.yaml` file with `require_conda: true`)

To solve this I've decided to rename the `require_conda` to `conda` and default it to `True`. I've also added a `--no-conda` option to the `snk install` command. So now you can run:

```bash
snk install nextstrain/ncov --commit 024910d7 --no-conda
```

And that will set `conda: false` in the `snk.yaml` file in the nextstrain/ncov pipeline. 

This is available in [v0.19.0](https://github.com/Wytamma/snk/releases/tag/v0.19.0).

-W
